# Generated by Django 5.0.6 on 2024-06-01 14:16

import Mesbah.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesbah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='url',
            field=models.FileField(upload_to=Mesbah.utils.RandomFileName('podcast_files'), verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.FileField(upload_to=Mesbah.utils.RandomFileName('podcast_files'), verbose_name='url'),
        ),
    ]
