# Generated by Django 5.0.6 on 2024-06-01 14:18

import Mesbah.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesbah', '0002_alter_clip_url_alter_podcast_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='url',
            field=models.FileField(upload_to=Mesbah.utils.RandomFileName('clip_files'), verbose_name='url'),
        ),
    ]
