# Generated by Django 5.0.6 on 2024-06-13 21:19

import Mesbah.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesbah', '0005_auditory_contactus_martyr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditory',
            options={'verbose_name_plural': 'auditories'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='clip',
            options={'verbose_name_plural': 'clips'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'contact us'},
        ),
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'verbose_name_plural': 'images album'},
        ),
        migrations.AlterModelOptions(
            name='martyr',
            options={'verbose_name_plural': 'martyrs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name_plural': 'podcasts'},
        ),
        migrations.AlterField(
            model_name='auditory',
            name='cover',
            field=models.ImageField(blank=True, upload_to='audio/audio_cover'),
        ),
        migrations.AlterField(
            model_name='auditory',
            name='url',
            field=models.FileField(upload_to=Mesbah.utils.RandomFileName('audio_files'), verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='cover',
            field=models.ImageField(blank=True, upload_to='martyr/martyr_cover'),
        ),
    ]
