# Generated by Django 5.0.6 on 2024-06-13 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesbah', '0006_alter_auditory_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name': 'podcast'},
        ),
        migrations.AlterField(
            model_name='auditory',
            name='cover',
            field=models.ImageField(blank=True, upload_to='audio/audio_cover', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='auditory',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='auditory',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='book',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book/book_cover', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(max_length=255, verbose_name='publish_date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='cover',
            field=models.ImageField(blank=True, upload_to='clip/clip_cover', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='identity',
            field=models.CharField(blank=True, max_length=500, verbose_name='identity'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='image',
            field=models.ImageField(blank=True, upload_to='album/album_cover', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='cover',
            field=models.ImageField(blank=True, upload_to='martyr/martyr_cover', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, upload_to='news/news_cover', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='news',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='news',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=500, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
